name: base_project
description: A new Flutter project.

version: 0.0.3+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Helpers
  intl: 0.17.0
  logger: 1.1.0
  url_launcher: 6.0.18
  device_info_plus: 3.2.1
  flutter_dotenv: 5.0.2

  # UI
  pretty_dio_logger: 1.2.0-beta-1
  google_fonts: 2.2.0
  cupertino_icons: 1.0.4

  # Http & Generation
  dio: 4.0.4
  get_it: 7.2.0
  injectable: 1.5.3
  retrofit: 3.0.1
  auto_route: 3.2.1
  json_annotation: 4.4.0
  freezed: 1.1.1
  
  # Architecture
  provider: 6.0.2
  rxdart: 0.27.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: 2.1.7
  hive_generator: 1.1.2
  json_serializable: 6.1.3
  auto_route_generator: 3.2.1
  retrofit_generator: 4.0.0
  injectable_generator: 1.5.3
  flutter_launcher_icons: 0.9.2
  freezed_annotation: 1.1.0


flutter:
  uses-material-design: true

  assets:
    - .local/
    # - assets/svg/
    # - assets/icons/
    # - assets/images/
    # - assets/translations/