name: base_project_template
description: A new Flutter project.

version: 0.5.4+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  build: 1.6.3

  # No nullsafety
  # get_version: 0.2.2


  # Helpers
  intl: 0.17.0
  logger: 0.9.4
  flutter_secure_storage: 4.1.0
  cross_connectivity: 3.0.1
  url_launcher: 6.0.2
  share: 2.0.1
  device_info: 2.0.0
  websafe_platform: 1.1.0
  
  # UI
  dio: 4.0.0-beta7  
  flutter_svg: 0.21.0-nullsafety.0
  google_fonts: 2.0.0
  cupertino_icons: 1.0.2
  carousel_slider: 3.0.0
  cached_network_image: 3.0.0-nullsafety
  flutter_screenutil: 4.0.3+3

  # Http & Generation
  pretty_dio_logger: 1.2.0-beta
  injectable: 1.2.0
  freezed_annotation: 0.14.0
  get_it: 6.0.0
  retrofit: 1.3.4+1

  # Architecture
  flutter_bloc: 6.1.3
  rxdart: 0.26.0
  # Firebase
  # firebase_core: 0.5.0+1
  # firebase_messaging: 7.0.3
  # firebase_database: 4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator:
    git:
      url: https://github.com/Chimerapps/retrofit.dart
      ref: feature/nullabilitysafe
      path: generator
  injectable_generator: 1.2.0
  flutter_launcher_icons: 0.9.0
  build_runner: 1.11.2
  freezed: 0.14.0+1

dependency_overrides:
  retrofit:
    git:
      url: https://github.com/Chimerapps/retrofit.dart
      ref: feature/nullabilitysafe
      path: annotation

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/mc_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/svg/loading.svg
    - assets/svgs/logo.svg
    - assets/svg/mc_logo.svg
    - assets/svg/close.svg
    - assets/svg/back_arrow.svg
    - assets/svg/handle.svg
    - assets/svg/another_catalog.svg
    - assets/svg/home.svg
    - assets/svg/logout.svg
    - assets/svg/settings.svg
    - assets/svg/switch.svg
    - assets/png/mc_logo.png

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/ubuntu/Ubuntu-Bold.ttf
        - asset: assets/ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
        - asset: assets/ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/ubuntu/Ubuntu-Light.ttf
        - asset: assets/ubuntu/Ubuntu-LightItalic.ttf
          style: italic
        - asset: assets/ubuntu/Ubuntu-Medium.ttf
        - asset: assets/ubuntu/Ubuntu-MediumItalic.ttf
          style: italic
        - asset: assets/ubuntu/Ubuntu-Regular.ttf

targets:
  $default:
    builders:
      retrofit_generator|retrofit:
        enabled: true
        options:
          nullsafety: true