/// Flutter icons BottomBar
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomBar
///      fonts:
///       - asset: fonts/BottomBar.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomBarIcons {
  BottomBarIcons._();

  static const _kFontFam = 'BottomBar';

  static const IconData home = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData favorites = IconData(0xe800, fontFamily: _kFontFam);
}
